/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const BRAKES: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        qualifying: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'The Stabiliser',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 2,
        cornering: 2,
        powerUnit: 1,
        qualifying: 3,
        pitStopTime: 0.97,
      },
      {
        level: 2,
        speed: 3,
        cornering: 3,
        powerUnit: 2,
        qualifying: 4,
        pitStopTime: 0.94,
      },
      {
        level: 3,
        speed: 4,
        cornering: 4,
        powerUnit: 3,
        qualifying: 5,
        pitStopTime: 0.91,
      },
      {
        level: 4,
        speed: 5,
        cornering: 5,
        powerUnit: 3,
        qualifying: 6,
        pitStopTime: 0.88,
      },
      {
        level: 5,
        speed: 6,
        cornering: 6,
        powerUnit: 4,
        qualifying: 7,
        pitStopTime: 0.85,
      },
      {
        level: 6,
        speed: 7,
        cornering: 7,
        powerUnit: 5,
        qualifying: 8,
        pitStopTime: 0.83,
      },
      {
        level: 7,
        speed: 7,
        cornering: 7,
        powerUnit: 6,
        qualifying: 8,
        pitStopTime: 0.80,
      },
      {
        level: 8,
        speed: 8,
        cornering: 8,
        powerUnit: 7,
        qualifying: 9,
        pitStopTime: 0.77,
      },
      {
        level: 9,
        speed: 9,
        cornering: 9,
        powerUnit: 7,
        qualifying: 10,
        pitStopTime: 0.74,
      },
      {
        level: 10,
        speed: 10,
        cornering: 10,
        powerUnit: 8,
        qualifying: 11,
        pitStopTime: 0.71,
      },
      {
        level: 11,
        speed: 11,
        cornering: 11,
        powerUnit: 9,
        qualifying: 12,
        pitStopTime: 0.69,
      },
    ],
  },
  {
    id: 2,
    name: 'The Corsair',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 3,
        cornering: 5,
        powerUnit: 2,
        qualifying: 1,
        pitStopTime: 0.86,
      },
      {
        level: 2,
        speed: 4,
        cornering: 7,
        powerUnit: 3,
        qualifying: 2,
        pitStopTime: 0.81,
      },
      {
        level: 3,
        speed: 4,
        cornering: 8,
        powerUnit: 3,
        qualifying: 2,
        pitStopTime: 0.77,
      },
      {
        level: 4,
        speed: 5,
        cornering: 10,
        powerUnit: 4,
        qualifying: 3,
        pitStopTime: 0.72,
      },
      {
        level: 5,
        speed: 5,
        cornering: 11,
        powerUnit: 4,
        qualifying: 3,
        pitStopTime: 0.68,
      },
      {
        level: 6,
        speed: 6,
        cornering: 13,
        powerUnit: 5,
        qualifying: 4,
        pitStopTime: 0.63,
      },
      {
        level: 7,
        speed: 6,
        cornering: 14,
        powerUnit: 5,
        qualifying: 4,
        pitStopTime: 0.59,
      },
      {
        level: 8,
        speed: 7,
        cornering: 16,
        powerUnit: 6,
        qualifying: 5,
        pitStopTime: 0.54,
      },
      {
        level: 9,
        speed: 7,
        cornering: 17,
        powerUnit: 6,
        qualifying: 5,
        pitStopTime: 0.50,
      },
      {
        level: 10,
        speed: 8,
        cornering: 19,
        powerUnit: 7,
        qualifying: 6,
        pitStopTime: 0.45,
      },
      {
        level: 11,
        speed: 8,
        cornering: 20,
        powerUnit: 7,
        qualifying: 6,
        pitStopTime: 0.41,
      },
    ],
  },
  {
    id: 3,
    name: 'The Fury',
    rarity: 'epic',
    series: 3,
    stats: [
      {
        level: 1,
        speed: 15,
        cornering: 5,
        powerUnit: 6,
        qualifying: 7,
        pitStopTime: 0.83,
      },
      {
        level: 2,
        speed: 18,
        cornering: 6,
        powerUnit: 7,
        qualifying: 8,
        pitStopTime: 0.80,
      },
      {
        level: 3,
        speed: 20,
        cornering: 7,
        powerUnit: 8,
        qualifying: 9,
        pitStopTime: 0.77,
      },
      {
        level: 4,
        speed: 23,
        cornering: 8,
        powerUnit: 9,
        qualifying: 10,
        pitStopTime: 0.74,
      },
      {
        level: 5,
        speed: 25,
        cornering: 8,
        powerUnit: 10,
        qualifying: 11,
        pitStopTime: 0.71,
      },
      {
        level: 6,
        speed: 28,
        cornering: 9,
        powerUnit: 11,
        qualifying: 12,
        pitStopTime: 0.68,
      },
      {
        level: 7,
        speed: 30,
        cornering: 10,
        powerUnit: 12,
        qualifying: 13,
        pitStopTime: 0.65,
      },
      {
        level: 8,
        speed: 33,
        cornering: 11,
        powerUnit: 13,
        qualifying: 14,
        pitStopTime: 0.62,
      },
    ],
  },
  {
    id: 4,
    name: 'Monolith',
    rarity: 'rare',
    series: 5,
    stats: [
      {
        level: 1,
        speed: 5,
        cornering: 15,
        powerUnit: 6,
        qualifying: 14,
        pitStopTime: 0.83,
      },
      {
        level: 2,
        speed: 6,
        cornering: 17,
        powerUnit: 7,
        qualifying: 16,
        pitStopTime: 0.80,
      },
      {
        level: 3,
        speed: 6,
        cornering: 19,
        powerUnit: 8,
        qualifying: 17,
        pitStopTime: 0.78,
      },
      {
        level: 4,
        speed: 7,
        cornering: 20,
        powerUnit: 8,
        qualifying: 19,
        pitStopTime: 0.76,
      },
      {
        level: 5,
        speed: 8,
        cornering: 22,
        powerUnit: 9,
        qualifying: 21,
        pitStopTime: 0.74,
      },
      {
        level: 6,
        speed: 8,
        cornering: 24,
        powerUnit: 10,
        qualifying: 22,
        pitStopTime: 0.72,
      },
      {
        level: 7,
        speed: 9,
        cornering: 26,
        powerUnit: 11,
        qualifying: 24,
        pitStopTime: 0.69,
      },
      {
        level: 8,
        speed: 9,
        cornering: 27,
        powerUnit: 11,
        qualifying: 25,
        pitStopTime: 0.67,
      },
      {
        level: 9,
        speed: 10,
        cornering: 29,
        powerUnit: 12,
        qualifying: 27,
        pitStopTime: 0.65,
      },
    ],
  },
  {
    id: 5,
    name: 'The Dynamo',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        speed: 8,
        cornering: 10,
        powerUnit: 28,
        qualifying: 11,
        pitStopTime: 0.69,
      },
      {
        level: 2,
        speed: 9,
        cornering: 11,
        powerUnit: 30,
        qualifying: 12,
        pitStopTime: 0.65,
      },
      {
        level: 3,
        speed: 10,
        cornering: 12,
        powerUnit: 32,
        qualifying: 13,
        pitStopTime: 0.62,
      },
      {
        level: 4,
        speed: 11,
        cornering: 13,
        powerUnit: 34,
        qualifying: 14,
        pitStopTime: 0.59,
      },
      {
        level: 5,
        speed: 12,
        cornering: 14,
        powerUnit: 36,
        qualifying: 15,
        pitStopTime: 0.56,
      },
      {
        level: 6,
        speed: 12,
        cornering: 15,
        powerUnit: 38,
        qualifying: 16,
        pitStopTime: 0.53,
      },
      {
        level: 7,
        speed: 13,
        cornering: 16,
        powerUnit: 40,
        qualifying: 17,
        pitStopTime: 0.50,
      },
      {
        level: 8,
        speed: 14,
        cornering: 17,
        powerUnit: 42,
        qualifying: 18,
        pitStopTime: 0.47,
      },
      {
        level: 9,
        speed: 15,
        cornering: 18,
        powerUnit: 44,
        qualifying: 19,
        pitStopTime: 0.44,
      },
    ],
  },
  {
    id: 6,
    name: 'Stormbringer',
    rarity: 'rare',
    series: 10,
    stats: [
      {
        level: 1,
        speed: 33,
        cornering: 12,
        powerUnit: 13,
        qualifying: 11,
        pitStopTime: 0.62,
      },
      {
        level: 2,
        speed: 35,
        cornering: 13,
        powerUnit: 14,
        qualifying: 12,
        pitStopTime: 0.59,
      },
      {
        level: 3,
        speed: 38,
        cornering: 14,
        powerUnit: 15,
        qualifying: 13,
        pitStopTime: 0.57,
      },
      {
        level: 4,
        speed: 40,
        cornering: 15,
        powerUnit: 16,
        qualifying: 14,
        pitStopTime: 0.55,
      },
      {
        level: 5,
        speed: 42,
        cornering: 16,
        powerUnit: 17,
        qualifying: 15,
        pitStopTime: 0.53,
      },
      {
        level: 6,
        speed: 44,
        cornering: 17,
        powerUnit: 18,
        qualifying: 16,
        pitStopTime: 0.51,
      },
      {
        level: 7,
        speed: 47,
        cornering: 18,
        powerUnit: 19,
        qualifying: 17,
        pitStopTime: 0.48,
      },
      {
        level: 8,
        speed: 49,
        cornering: 19,
        powerUnit: 20,
        qualifying: 18,
        pitStopTime: 0.46,
      },
      {
        level: 9,
        speed: 51,
        cornering: 20,
        powerUnit: 21,
        qualifying: 19,
        pitStopTime: 0.44,
      },
    ],
  },
  {
    id: 7,
    name: 'The Behemoth',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        speed: 16,
        cornering: 42,
        powerUnit: 17,
        qualifying: 14,
        pitStopTime: 0.44,
      },
      {
        level: 2,
        speed: 17,
        cornering: 45,
        powerUnit: 18,
        qualifying: 15,
        pitStopTime: 0.41,
      },
      {
        level: 3,
        speed: 18,
        cornering: 47,
        powerUnit: 19,
        qualifying: 16,
        pitStopTime: 0.37,
      },
      {
        level: 4,
        speed: 19,
        cornering: 50,
        powerUnit: 20,
        qualifying: 17,
        pitStopTime: 0.34,
      },
      {
        level: 5,
        speed: 19,
        cornering: 52,
        powerUnit: 20,
        qualifying: 18,
        pitStopTime: 0.30,
      },
      {
        level: 6,
        speed: 20,
        cornering: 55,
        powerUnit: 21,
        qualifying: 19,
        pitStopTime: 0.27,
      },
      {
        level: 7,
        speed: 21,
        cornering: 57,
        powerUnit: 22,
        qualifying: 20,
        pitStopTime: 0.23,
      },
      {
        level: 8,
        speed: 22,
        cornering: 60,
        powerUnit: 23,
        qualifying: 21,
        pitStopTime: 0.20,
      },
    ],
  },
] as Part[];

const createBrakes = () => {
  const brakesToSave = preparePartData(BRAKES);

  console.log('Creating brakes file >>');
  createFile('src/features/parts/constants/brakes.json', brakesToSave);
};

export default createBrakes;
