/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const ENGINES: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'The Synergy',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 2,
        cornering: 3,
        powerUnit: 1,
        qualifying: 2,
        pitStopTime: 0.97,
      },
      {
        level: 2,
        speed: 3,
        cornering: 4,
        powerUnit: 2,
        qualifying: 3,
        pitStopTime: 0.94,
      },
      {
        level: 3,
        speed: 4,
        cornering: 5,
        powerUnit: 3,
        qualifying: 4,
        pitStopTime: 0.91,
      },
      {
        level: 4,
        speed: 5,
        cornering: 6,
        powerUnit: 3,
        qualifying: 5,
        pitStopTime: 0.88,
      },
      {
        level: 5,
        speed: 6,
        cornering: 7,
        powerUnit: 4,
        qualifying: 6,
        pitStopTime: 0.85,
      },
      {
        level: 6,
        speed: 7,
        cornering: 8,
        powerUnit: 5,
        qualifying: 7,
        pitStopTime: 0.83,
      },
      {
        level: 7,
        speed: 7,
        cornering: 8,
        powerUnit: 6,
        qualifying: 7,
        pitStopTime: 0.80,
      },
      {
        level: 8,
        speed: 8,
        cornering: 9,
        powerUnit: 7,
        qualifying: 8,
        pitStopTime: 0.77,
      },
      {
        level: 9,
        speed: 9,
        cornering: 10,
        powerUnit: 7,
        qualifying: 9,
        pitStopTime: 0.74,
      },
      {
        level: 10,
        speed: 10,
        cornering: 11,
        powerUnit: 8,
        qualifying: 10,
        pitStopTime: 0.71,
      },
      {
        level: 11,
        speed: 11,
        cornering: 12,
        powerUnit: 9,
        qualifying: 11,
        pitStopTime: 0.69,
      },
    ],
  },
  {
    id: 2,
    name: 'The Accord',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 6,
        cornering: 2,
        powerUnit: 1,
        qualifying: 3,
        pitStopTime: 0.90,
      },
      {
        level: 2,
        speed: 7,
        cornering: 3,
        powerUnit: 2,
        qualifying: 4,
        pitStopTime: 0.85,
      },
      {
        level: 3,
        speed: 8,
        cornering: 3,
        powerUnit: 2,
        qualifying: 4,
        pitStopTime: 0.81,
      },
      {
        level: 4,
        speed: 10,
        cornering: 4,
        powerUnit: 3,
        qualifying: 5,
        pitStopTime: 0.77,
      },
      {
        level: 5,
        speed: 11,
        cornering: 4,
        powerUnit: 3,
        qualifying: 6,
        pitStopTime: 0.73,
      },
      {
        level: 6,
        speed: 12,
        cornering: 5,
        powerUnit: 4,
        qualifying: 7,
        pitStopTime: 0.69,
      },
      {
        level: 7,
        speed: 13,
        cornering: 6,
        powerUnit: 5,
        qualifying: 7,
        pitStopTime: 0.64,
      },
      {
        level: 8,
        speed: 14,
        cornering: 6,
        powerUnit: 5,
        qualifying: 8,
        pitStopTime: 0.60,
      },
      {
        level: 9,
        speed: 16,
        cornering: 7,
        powerUnit: 6,
        qualifying: 9,
        pitStopTime: 0.56,
      },
      {
        level: 10,
        speed: 17,
        cornering: 7,
        powerUnit: 6,
        qualifying: 9,
        pitStopTime: 0.52,
      },
      {
        level: 11,
        speed: 18,
        cornering: 8,
        powerUnit: 7,
        qualifying: 10,
        pitStopTime: 0.48,
      },
    ],
  },
  {
    id: 3,
    name: 'Thunderbolt',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        speed: 6,
        cornering: 12,
        powerUnit: 5,
        qualifying: 4,
        pitStopTime: 0.86,
      },
      {
        level: 2,
        speed: 7,
        cornering: 14,
        powerUnit: 6,
        qualifying: 5,
        pitStopTime: 0.84,
      },
      {
        level: 3,
        speed: 7,
        cornering: 16,
        powerUnit: 6,
        qualifying: 5,
        pitStopTime: 0.81,
      },
      {
        level: 4,
        speed: 8,
        cornering: 18,
        powerUnit: 7,
        qualifying: 6,
        pitStopTime: 0.79,
      },
      {
        level: 5,
        speed: 8,
        cornering: 20,
        powerUnit: 7,
        qualifying: 6,
        pitStopTime: 0.76,
      },
      {
        level: 6,
        speed: 9,
        cornering: 22,
        powerUnit: 8,
        qualifying: 7,
        pitStopTime: 0.74,
      },
      {
        level: 7,
        speed: 10,
        cornering: 23,
        powerUnit: 9,
        qualifying: 7,
        pitStopTime: 0.71,
      },
      {
        level: 8,
        speed: 10,
        cornering: 25,
        powerUnit: 9,
        qualifying: 8,
        pitStopTime: 0.69,
      },
      {
        level: 9,
        speed: 11,
        cornering: 27,
        powerUnit: 10,
        qualifying: 8,
        pitStopTime: 0.66,
      },
      {
        level: 10,
        speed: 11,
        cornering: 29,
        powerUnit: 10,
        qualifying: 9,
        pitStopTime: 0.64,
      },
      {
        level: 11,
        speed: 12,
        cornering: 31,
        powerUnit: 11,
        qualifying: 9,
        pitStopTime: 0.62,
      },
    ],
  },
  {
    id: 4,
    name: 'M4D Dash',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        speed: 8,
        cornering: 6,
        powerUnit: 16,
        qualifying: 16,
        pitStopTime: 0.79,
      },
      {
        level: 2,
        speed: 9,
        cornering: 7,
        powerUnit: 18,
        qualifying: 18,
        pitStopTime: 0.77,
      },
      {
        level: 3,
        speed: 10,
        cornering: 8,
        powerUnit: 20,
        qualifying: 19,
        pitStopTime: 0.75,
      },
      {
        level: 4,
        speed: 10,
        cornering: 8,
        powerUnit: 21,
        qualifying: 21,
        pitStopTime: 0.72,
      },
      {
        level: 5,
        speed: 11,
        cornering: 9,
        powerUnit: 23,
        qualifying: 23,
        pitStopTime: 0.70,
      },
      {
        level: 6,
        speed: 12,
        cornering: 10,
        powerUnit: 25,
        qualifying: 24,
        pitStopTime: 0.68,
      },
      {
        level: 7,
        speed: 13,
        cornering: 11,
        powerUnit: 27,
        qualifying: 26,
        pitStopTime: 0.66,
      },
      {
        level: 8,
        speed: 13,
        cornering: 11,
        powerUnit: 28,
        qualifying: 27,
        pitStopTime: 0.64,
      },
      {
        level: 9,
        speed: 14,
        cornering: 12,
        powerUnit: 30,
        qualifying: 29,
        pitStopTime: 0.62,
      },
    ],
  },
  {
    id: 5,
    name: 'The Juggernaut',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        speed: 10,
        cornering: 24,
        powerUnit: 8,
        qualifying: 9,
        pitStopTime: 0.72,
      },
      {
        level: 2,
        speed: 11,
        cornering: 26,
        powerUnit: 9,
        qualifying: 10,
        pitStopTime: 0.69,
      },
      {
        level: 3,
        speed: 12,
        cornering: 29,
        powerUnit: 10,
        qualifying: 11,
        pitStopTime: 0.65,
      },
      {
        level: 4,
        speed: 12,
        cornering: 31,
        powerUnit: 10,
        qualifying: 11,
        pitStopTime: 0.62,
      },
      {
        level: 5,
        speed: 13,
        cornering: 34,
        powerUnit: 11,
        qualifying: 12,
        pitStopTime: 0.58,
      },
      {
        level: 6,
        speed: 14,
        cornering: 36,
        powerUnit: 12,
        qualifying: 13,
        pitStopTime: 0.55,
      },
      {
        level: 7,
        speed: 15,
        cornering: 38,
        powerUnit: 13,
        qualifying: 14,
        pitStopTime: 0.51,
      },
      {
        level: 8,
        speed: 15,
        cornering: 41,
        powerUnit: 13,
        qualifying: 14,
        pitStopTime: 0.48,
      },
      {
        level: 9,
        speed: 16,
        cornering: 43,
        powerUnit: 14,
        qualifying: 15,
        pitStopTime: 0.44,
      },
    ],
  },
  {
    id: 6,
    name: 'Mach III',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        speed: 36,
        cornering: 15,
        powerUnit: 13,
        qualifying: 14,
        pitStopTime: 0.55,
      },
      {
        level: 2,
        speed: 39,
        cornering: 16,
        powerUnit: 14,
        qualifying: 15,
        pitStopTime: 0.51,
      },
      {
        level: 3,
        speed: 41,
        cornering: 17,
        powerUnit: 15,
        qualifying: 16,
        pitStopTime: 0.48,
      },
      {
        level: 4,
        speed: 44,
        cornering: 18,
        powerUnit: 16,
        qualifying: 17,
        pitStopTime: 0.44,
      },
      {
        level: 5,
        speed: 46,
        cornering: 18,
        powerUnit: 16,
        qualifying: 17,
        pitStopTime: 0.41,
      },
      {
        level: 6,
        speed: 49,
        cornering: 19,
        powerUnit: 17,
        qualifying: 18,
        pitStopTime: 0.37,
      },
      {
        level: 7,
        speed: 51,
        cornering: 20,
        powerUnit: 18,
        qualifying: 19,
        pitStopTime: 0.34,
      },
      {
        level: 8,
        speed: 54,
        cornering: 21,
        powerUnit: 19,
        qualifying: 20,
        pitStopTime: 0.30,
      },
    ],
  },
  {
    id: 7,
    name: 'The Powerhouse',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        speed: 15,
        cornering: 16,
        powerUnit: 42,
        qualifying: 17,
        pitStopTime: 0.48,
      },
      {
        level: 2,
        speed: 16,
        cornering: 17,
        powerUnit: 45,
        qualifying: 18,
        pitStopTime: 0.45,
      },
      {
        level: 3,
        speed: 17,
        cornering: 18,
        powerUnit: 47,
        qualifying: 19,
        pitStopTime: 0.43,
      },
      {
        level: 4,
        speed: 18,
        cornering: 19,
        powerUnit: 50,
        qualifying: 20,
        pitStopTime: 0.40,
      },
      {
        level: 5,
        speed: 18,
        cornering: 20,
        powerUnit: 52,
        qualifying: 22,
        pitStopTime: 0.38,
      },
      {
        level: 6,
        speed: 19,
        cornering: 21,
        powerUnit: 55,
        qualifying: 23,
        pitStopTime: 0.35,
      },
      {
        level: 7,
        speed: 20,
        cornering: 22,
        powerUnit: 57,
        qualifying: 24,
        pitStopTime: 0.33,
      },
      {
        level: 8,
        speed: 21,
        cornering: 23,
        powerUnit: 60,
        qualifying: 25,
        pitStopTime: 0.30,
      },
    ],
  },
] as Part[];

const createEngines = () => {
  const enginesToSave = preparePartData(ENGINES);

  console.log('Creating engines file >>');
  createFile('src/features/parts/constants/engines.json', enginesToSave);
};

export default createEngines;
