/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const FRONT_WINGS: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'Glide',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 2,
        cornering: 2,
        powerUnit: 3,
        qualifying: 1,
        pitStopTime: 0.97,
      },
      {
        level: 2,
        speed: 3,
        cornering: 3,
        powerUnit: 4,
        qualifying: 2,
        pitStopTime: 0.94,
      },
      {
        level: 3,
        speed: 4,
        cornering: 4,
        powerUnit: 5,
        qualifying: 3,
        pitStopTime: 0.92,
      },
      {
        level: 4,
        speed: 5,
        cornering: 4,
        powerUnit: 6,
        qualifying: 4,
        pitStopTime: 0.89,
      },
      {
        level: 5,
        speed: 6,
        cornering: 5,
        powerUnit: 7,
        qualifying: 5,
        pitStopTime: 0.87,
      },
      {
        level: 6,
        speed: 7,
        cornering: 6,
        powerUnit: 8,
        qualifying: 6,
        pitStopTime: 0.84,
      },
      {
        level: 7,
        speed: 7,
        cornering: 7,
        powerUnit: 8,
        qualifying: 7,
        pitStopTime: 0.82,
      },
      {
        level: 8,
        speed: 8,
        cornering: 8,
        powerUnit: 9,
        qualifying: 8,
        pitStopTime: 0.79,
      },
      {
        level: 9,
        speed: 9,
        cornering: 8,
        powerUnit: 10,
        qualifying: 9,
        pitStopTime: 0.77,
      },
      {
        level: 10,
        speed: 10,
        cornering: 9,
        powerUnit: 11,
        qualifying: 10,
        pitStopTime: 0.74,
      },
      {
        level: 11,
        speed: 11,
        cornering: 10,
        powerUnit: 12,
        qualifying: 11,
        pitStopTime: 0.72,
      },
    ],
  },
  {
    id: 2,
    name: 'Gallop',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 5,
        cornering: 2,
        powerUnit: 2,
        qualifying: 4,
        pitStopTime: 0.97,
      },
      {
        level: 2,
        speed: 6,
        cornering: 3,
        powerUnit: 3,
        qualifying: 5,
        pitStopTime: 0.94,
      },
      {
        level: 3,
        speed: 8,
        cornering: 3,
        powerUnit: 3,
        qualifying: 6,
        pitStopTime: 0.92,
      },
      {
        level: 4,
        speed: 9,
        cornering: 4,
        powerUnit: 4,
        qualifying: 8,
        pitStopTime: 0.89,
      },
      {
        level: 5,
        speed: 10,
        cornering: 4,
        powerUnit: 4,
        qualifying: 9,
        pitStopTime: 0.87,
      },
      {
        level: 6,
        speed: 12,
        cornering: 5,
        powerUnit: 5,
        qualifying: 10,
        pitStopTime: 0.84,
      },
      {
        level: 7,
        speed: 13,
        cornering: 6,
        powerUnit: 6,
        qualifying: 11,
        pitStopTime: 0.82,
      },
      {
        level: 8,
        speed: 14,
        cornering: 6,
        powerUnit: 6,
        qualifying: 12,
        pitStopTime: 0.79,
      },
      {
        level: 9,
        speed: 15,
        cornering: 7,
        powerUnit: 7,
        qualifying: 14,
        pitStopTime: 0.77,
      },
      {
        level: 10,
        speed: 17,
        cornering: 7,
        powerUnit: 7,
        qualifying: 15,
        pitStopTime: 0.74,
      },
      {
        level: 11,
        speed: 18,
        cornering: 8,
        powerUnit: 8,
        qualifying: 16,
        pitStopTime: 0.72,
      },
    ],
  },
  {
    id: 3,
    name: 'Spark E',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        speed: 4,
        cornering: 3,
        powerUnit: 7,
        qualifying: 2,
        pitStopTime: 0.79,
      },
      {
        level: 2,
        speed: 5,
        cornering: 4,
        powerUnit: 8,
        qualifying: 3,
        pitStopTime: 0.74,
      },
      {
        level: 3,
        speed: 5,
        cornering: 4,
        powerUnit: 10,
        qualifying: 3,
        pitStopTime: 0.69,
      },
      {
        level: 4,
        speed: 6,
        cornering: 5,
        powerUnit: 11,
        qualifying: 4,
        pitStopTime: 0.64,
      },
      {
        level: 5,
        speed: 6,
        cornering: 5,
        powerUnit: 13,
        qualifying: 4,
        pitStopTime: 0.59,
      },
      {
        level: 6,
        speed: 7,
        cornering: 6,
        powerUnit: 14,
        qualifying: 5,
        pitStopTime: 0.55,
      },
      {
        level: 7,
        speed: 8,
        cornering: 7,
        powerUnit: 15,
        qualifying: 5,
        pitStopTime: 0.50,
      },
      {
        level: 8,
        speed: 8,
        cornering: 7,
        powerUnit: 17,
        qualifying: 6,
        pitStopTime: 0.45,
      },
      {
        level: 9,
        speed: 9,
        cornering: 8,
        powerUnit: 18,
        qualifying: 6,
        pitStopTime: 0.40,
      },
      {
        level: 10,
        speed: 9,
        cornering: 8,
        powerUnit: 20,
        qualifying: 7,
        pitStopTime: 0.35,
      },
      {
        level: 11,
        speed: 10,
        cornering: 9,
        powerUnit: 21,
        qualifying: 7,
        pitStopTime: 0.30,
      },
    ],
  },
  {
    id: 4,
    name: 'The Saber',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        speed: 6,
        cornering: 15,
        powerUnit: 5,
        qualifying: 13,
        pitStopTime: 0.79,
      },
      {
        level: 2,
        speed: 7,
        cornering: 17,
        powerUnit: 6,
        qualifying: 15,
        pitStopTime: 0.77,
      },
      {
        level: 3,
        speed: 7,
        cornering: 19,
        powerUnit: 7,
        qualifying: 16,
        pitStopTime: 0.75,
      },
      {
        level: 4,
        speed: 8,
        cornering: 20,
        powerUnit: 7,
        qualifying: 18,
        pitStopTime: 0.72,
      },
      {
        level: 5,
        speed: 9,
        cornering: 22,
        powerUnit: 8,
        qualifying: 20,
        pitStopTime: 0.70,
      },
      {
        level: 6,
        speed: 9,
        cornering: 24,
        powerUnit: 9,
        qualifying: 21,
        pitStopTime: 0.68,
      },
      {
        level: 7,
        speed: 10,
        cornering: 26,
        powerUnit: 10,
        qualifying: 23,
        pitStopTime: 0.66,
      },
      {
        level: 8,
        speed: 10,
        cornering: 27,
        powerUnit: 10,
        qualifying: 24,
        pitStopTime: 0.64,
      },
      {
        level: 9,
        speed: 11,
        cornering: 29,
        powerUnit: 11,
        qualifying: 26,
        pitStopTime: 0.62,
      },
    ],
  },
  {
    id: 5,
    name: 'Turbo Jet',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        speed: 24,
        cornering: 10,
        powerUnit: 8,
        qualifying: 9,
        pitStopTime: 0.72,
      },
      {
        level: 2,
        speed: 26,
        cornering: 11,
        powerUnit: 9,
        qualifying: 10,
        pitStopTime: 0.69,
      },
      {
        level: 3,
        speed: 29,
        cornering: 12,
        powerUnit: 10,
        qualifying: 11,
        pitStopTime: 0.67,
      },
      {
        level: 4,
        speed: 31,
        cornering: 13,
        powerUnit: 10,
        qualifying: 11,
        pitStopTime: 0.64,
      },
      {
        level: 5,
        speed: 34,
        cornering: 14,
        powerUnit: 11,
        qualifying: 12,
        pitStopTime: 0.62,
      },
      {
        level: 6,
        speed: 36,
        cornering: 15,
        powerUnit: 12,
        qualifying: 13,
        pitStopTime: 0.59,
      },
      {
        level: 7,
        speed: 38,
        cornering: 16,
        powerUnit: 13,
        qualifying: 14,
        pitStopTime: 0.56,
      },
      {
        level: 8,
        speed: 41,
        cornering: 17,
        powerUnit: 13,
        qualifying: 14,
        pitStopTime: 0.54,
      },
      {
        level: 9,
        speed: 43,
        cornering: 18,
        powerUnit: 14,
        qualifying: 15,
        pitStopTime: 0.51,
      },
    ],
  },
  {
    id: 6,
    name: 'The Beast',
    rarity: 'epic',
    series: 9,
    stats: [
      {
        level: 1,
        speed: 13,
        cornering: 14,
        powerUnit: 35,
        qualifying: 15,
        pitStopTime: 0.58,
      },
      {
        level: 2,
        speed: 14,
        cornering: 15,
        powerUnit: 38,
        qualifying: 16,
        pitStopTime: 0.55,
      },
      {
        level: 3,
        speed: 15,
        cornering: 16,
        powerUnit: 40,
        qualifying: 17,
        pitStopTime: 0.52,
      },
      {
        level: 4,
        speed: 16,
        cornering: 17,
        powerUnit: 43,
        qualifying: 18,
        pitStopTime: 0.49,
      },
      {
        level: 5,
        speed: 16,
        cornering: 18,
        powerUnit: 46,
        qualifying: 19,
        pitStopTime: 0.46,
      },
      {
        level: 6,
        speed: 17,
        cornering: 19,
        powerUnit: 49,
        qualifying: 20,
        pitStopTime: 0.43,
      },
      {
        level: 7,
        speed: 18,
        cornering: 20,
        powerUnit: 51,
        qualifying: 21,
        pitStopTime: 0.40,
      },
      {
        level: 8,
        speed: 19,
        cornering: 21,
        powerUnit: 54,
        qualifying: 22,
        pitStopTime: 0.37,
      },
    ],
  },
  {
    id: 7,
    name: 'Nemesis',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        speed: 17,
        cornering: 42,
        powerUnit: 15,
        qualifying: 16,
        pitStopTime: 0.48,
      },
      {
        level: 2,
        speed: 18,
        cornering: 45,
        powerUnit: 16,
        qualifying: 17,
        pitStopTime: 0.45,
      },
      {
        level: 3,
        speed: 19,
        cornering: 47,
        powerUnit: 17,
        qualifying: 18,
        pitStopTime: 0.43,
      },
      {
        level: 4,
        speed: 20,
        cornering: 50,
        powerUnit: 18,
        qualifying: 19,
        pitStopTime: 0.40,
      },
      {
        level: 5,
        speed: 22,
        cornering: 52,
        powerUnit: 18,
        qualifying: 20,
        pitStopTime: 0.38,
      },
      {
        level: 6,
        speed: 23,
        cornering: 55,
        powerUnit: 19,
        qualifying: 21,
        pitStopTime: 0.35,
      },
      {
        level: 7,
        speed: 24,
        cornering: 57,
        powerUnit: 20,
        qualifying: 22,
        pitStopTime: 0.33,
      },
      {
        level: 8,
        speed: 25,
        cornering: 60,
        powerUnit: 21,
        qualifying: 23,
        pitStopTime: 0.30,
      },
    ],
  },
] as Part[];

const createFrontWings = () => {
  const frontWingsToSave = preparePartData(FRONT_WINGS);

  console.log('Creating front wings file >>');
  createFile('src/features/parts/constants/frontWings.json', frontWingsToSave);
};

export default createFrontWings;
