/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const GEARBOXES: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        qual: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'The Equinox',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 2,
        cornering: 2,
        powerUnit: 3,
        qualifying: 1,
        pitStopTime: 0.97,
      },
      {
        level: 2,
        speed: 3,
        cornering: 3,
        powerUnit: 4,
        qualifying: 2,
        pitStopTime: 0.93,
      },
      {
        level: 3,
        speed: 4,
        cornering: 4,
        powerUnit: 5,
        qualifying: 3,
        pitStopTime: 0.90,
      },
      {
        level: 4,
        speed: 4,
        cornering: 5,
        powerUnit: 6,
        qualifying: 3,
        pitStopTime: 0.87,
      },
      {
        level: 5,
        speed: 5,
        cornering: 6,
        powerUnit: 7,
        qualifying: 4,
        pitStopTime: 0.84,
      },
      {
        level: 6,
        speed: 6,
        cornering: 7,
        powerUnit: 8,
        qualifying: 5,
        pitStopTime: 0.81,
      },
      {
        level: 7,
        speed: 7,
        cornering: 7,
        powerUnit: 8,
        qualifying: 6,
        pitStopTime: 0.78,
      },
      {
        level: 8,
        speed: 8,
        cornering: 8,
        powerUnit: 9,
        qualifying: 7,
        pitStopTime: 0.74,
      },
      {
        level: 9,
        speed: 8,
        cornering: 9,
        powerUnit: 10,
        qualifying: 7,
        pitStopTime: 0.71,
      },
      {
        level: 10,
        speed: 9,
        cornering: 10,
        powerUnit: 11,
        qualifying: 8,
        pitStopTime: 0.68,
      },
      {
        level: 11,
        speed: 10,
        cornering: 11,
        powerUnit: 12,
        qualifying: 9,
        pitStopTime: 0.65,
      },
    ],
  },
  {
    id: 2,
    name: 'Cold Fusion',
    rarity: 'rare',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 3,
        cornering: 2,
        powerUnit: 7,
        qualifying: 7,
        pitStopTime: 0.90,
      },
      {
        level: 2,
        speed: 4,
        cornering: 3,
        powerUnit: 9,
        qualifying: 9,
        pitStopTime: 0.87,
      },
      {
        level: 3,
        speed: 4,
        cornering: 3,
        powerUnit: 11,
        qualifying: 11,
        pitStopTime: 0.84,
      },
      {
        level: 4,
        speed: 5,
        cornering: 4,
        powerUnit: 12,
        qualifying: 12,
        pitStopTime: 0.82,
      },
      {
        level: 5,
        speed: 6,
        cornering: 5,
        powerUnit: 14,
        qualifying: 14,
        pitStopTime: 0.79,
      },
      {
        level: 6,
        speed: 6,
        cornering: 5,
        powerUnit: 16,
        qualifying: 16,
        pitStopTime: 0.76,
      },
      {
        level: 7,
        speed: 7,
        cornering: 6,
        powerUnit: 18,
        qualifying: 18,
        pitStopTime: 0.74,
      },
      {
        level: 8,
        speed: 7,
        cornering: 6,
        powerUnit: 19,
        qualifying: 19,
        pitStopTime: 0.71,
      },
      {
        level: 9,
        speed: 8,
        cornering: 7,
        powerUnit: 21,
        qualifying: 21,
        pitStopTime: 0.69,
      },
    ],
  },
  {
    id: 3,
    name: 'Pivot',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        speed: 2,
        cornering: 8,
        powerUnit: 4,
        qualifying: 2,
        pitStopTime: 0.79,
      },
      {
        level: 2,
        speed: 3,
        cornering: 9,
        powerUnit: 5,
        qualifying: 3,
        pitStopTime: 0.74,
      },
      {
        level: 3,
        speed: 3,
        cornering: 11,
        powerUnit: 5,
        qualifying: 3,
        pitStopTime: 0.69,
      },
      {
        level: 4,
        speed: 4,
        cornering: 12,
        powerUnit: 6,
        qualifying: 4,
        pitStopTime: 0.64,
      },
      {
        level: 5,
        speed: 4,
        cornering: 14,
        powerUnit: 7,
        qualifying: 4,
        pitStopTime: 0.59,
      },
      {
        level: 6,
        speed: 5,
        cornering: 15,
        powerUnit: 8,
        qualifying: 5,
        pitStopTime: 0.55,
      },
      {
        level: 7,
        speed: 5,
        cornering: 16,
        powerUnit: 8,
        qualifying: 5,
        pitStopTime: 0.50,
      },
      {
        level: 8,
        speed: 6,
        cornering: 18,
        powerUnit: 9,
        qualifying: 6,
        pitStopTime: 0.45,
      },
      {
        level: 9,
        speed: 6,
        cornering: 19,
        powerUnit: 10,
        qualifying: 6,
        pitStopTime: 0.40,
      },
      {
        level: 10,
        speed: 7,
        cornering: 21,
        powerUnit: 10,
        qualifying: 7,
        pitStopTime: 0.35,
      },
      {
        level: 11,
        speed: 7,
        cornering: 22,
        powerUnit: 11,
        qualifying: 7,
        pitStopTime: 0.30,
      },
    ],
  },
  {
    id: 4,
    name: 'The Surge',
    rarity: 'epic',
    series: 5,
    stats: [
      {
        level: 1,
        speed: 17,
        cornering: 5,
        powerUnit: 7,
        qualifying: 16,
        pitStopTime: 0.76,
      },
      {
        level: 2,
        speed: 19,
        cornering: 6,
        powerUnit: 8,
        qualifying: 18,
        pitStopTime: 0.72,
      },
      {
        level: 3,
        speed: 21,
        cornering: 7,
        powerUnit: 9,
        qualifying: 19,
        pitStopTime: 0.69,
      },
      {
        level: 4,
        speed: 23,
        cornering: 8,
        powerUnit: 10,
        qualifying: 21,
        pitStopTime: 0.65,
      },
      {
        level: 5,
        speed: 24,
        cornering: 8,
        powerUnit: 10,
        qualifying: 23,
        pitStopTime: 0.62,
      },
      {
        level: 6,
        speed: 26,
        cornering: 9,
        powerUnit: 11,
        qualifying: 25,
        pitStopTime: 0.58,
      },
      {
        level: 7,
        speed: 28,
        cornering: 10,
        powerUnit: 12,
        qualifying: 26,
        pitStopTime: 0.55,
      },
      {
        level: 8,
        speed: 30,
        cornering: 11,
        powerUnit: 13,
        qualifying: 28,
        pitStopTime: 0.51,
      },
    ],
  },
  {
    id: 5,
    name: 'The Quantum',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        speed: 11,
        cornering: 8,
        powerUnit: 27,
        qualifying: 11,
        pitStopTime: 0.69,
      },
      {
        level: 2,
        speed: 12,
        cornering: 9,
        powerUnit: 29,
        qualifying: 12,
        pitStopTime: 0.65,
      },
      {
        level: 3,
        speed: 13,
        cornering: 10,
        powerUnit: 31,
        qualifying: 13,
        pitStopTime: 0.62,
      },
      {
        level: 4,
        speed: 14,
        cornering: 11,
        powerUnit: 33,
        qualifying: 14,
        pitStopTime: 0.58,
      },
      {
        level: 5,
        speed: 15,
        cornering: 12,
        powerUnit: 36,
        qualifying: 15,
        pitStopTime: 0.55,
      },
      {
        level: 6,
        speed: 15,
        cornering: 12,
        powerUnit: 38,
        qualifying: 15,
        pitStopTime: 0.51,
      },
      {
        level: 7,
        speed: 16,
        cornering: 13,
        powerUnit: 40,
        qualifying: 16,
        pitStopTime: 0.48,
      },
      {
        level: 8,
        speed: 17,
        cornering: 14,
        powerUnit: 42,
        qualifying: 17,
        pitStopTime: 0.44,
      },
      {
        level: 9,
        speed: 18,
        cornering: 15,
        powerUnit: 44,
        qualifying: 18,
        pitStopTime: 0.41,
      },
    ],
  },
  {
    id: 6,
    name: 'The Gyro',
    rarity: 'rare',
    series: 10,
    stats: [
      {
        level: 1,
        speed: 12,
        cornering: 33,
        powerUnit: 10,
        qualifying: 14,
        pitStopTime: 0.65,
      },
      {
        level: 2,
        speed: 13,
        cornering: 36,
        powerUnit: 11,
        qualifying: 15,
        pitStopTime: 0.62,
      },
      {
        level: 3,
        speed: 14,
        cornering: 38,
        powerUnit: 12,
        qualifying: 16,
        pitStopTime: 0.58,
      },
      {
        level: 4,
        speed: 15,
        cornering: 41,
        powerUnit: 13,
        qualifying: 16,
        pitStopTime: 0.55,
      },
      {
        level: 5,
        speed: 16,
        cornering: 43,
        powerUnit: 14,
        qualifying: 17,
        pitStopTime: 0.51,
      },
      {
        level: 6,
        speed: 16,
        cornering: 46,
        powerUnit: 14,
        qualifying: 18,
        pitStopTime: 0.48,
      },
      {
        level: 7,
        speed: 17,
        cornering: 48,
        powerUnit: 15,
        qualifying: 19,
        pitStopTime: 0.44,
      },
      {
        level: 8,
        speed: 18,
        cornering: 51,
        powerUnit: 16,
        qualifying: 19,
        pitStopTime: 0.41,
      },
      {
        level: 9,
        speed: 19,
        cornering: 53,
        powerUnit: 17,
        qualifying: 20,
        pitStopTime: 0.37,
      },
    ],
  },
  {
    id: 7,
    name: 'Beat',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        speed: 42,
        cornering: 15,
        powerUnit: 17,
        qualifying: 16,
        pitStopTime: 0.48,
      },
      {
        level: 2,
        speed: 44,
        cornering: 16,
        powerUnit: 18,
        qualifying: 17,
        pitStopTime: 0.45,
      },
      {
        level: 3,
        speed: 47,
        cornering: 17,
        powerUnit: 19,
        qualifying: 18,
        pitStopTime: 0.42,
      },
      {
        level: 4,
        speed: 49,
        cornering: 17,
        powerUnit: 20,
        qualifying: 19,
        pitStopTime: 0.40,
      },
      {
        level: 5,
        speed: 51,
        cornering: 18,
        powerUnit: 21,
        qualifying: 20,
        pitStopTime: 0.37,
      },
      {
        level: 6,
        speed: 53,
        cornering: 19,
        powerUnit: 21,
        qualifying: 20,
        pitStopTime: 0.34,
      },
      {
        level: 7,
        speed: 56,
        cornering: 20,
        powerUnit: 22,
        qualifying: 21,
        pitStopTime: 0.32,
      },
      {
        level: 8,
        speed: 60,
        cornering: 21,
        powerUnit: 24,
        qualifying: 23,
        pitStopTime: 0.27,
      },
    ],
  },
] as Part[];

const createGearboxes = () => {
  const gearboxesToSave = preparePartData(GEARBOXES);

  console.log('Creating gearboxes file >>');
  createFile('src/features/parts/constants/gearboxes.json', gearboxesToSave);
};

export default createGearboxes;
