/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const REAR_WINGS: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'The Blaze',
    rarity: 'rare',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 6,
        powerUnit: 3,
        qualifying: 2,
        pitStopTime: 0.97,
      },
      {
        level: 2,
        speed: 2,
        cornering: 8,
        powerUnit: 4,
        qualifying: 3,
        pitStopTime: 0.94,
      },
      {
        level: 3,
        speed: 3,
        cornering: 11,
        powerUnit: 5,
        qualifying: 4,
        pitStopTime: 0.91,
      },
      {
        level: 4,
        speed: 4,
        cornering: 13,
        powerUnit: 6,
        qualifying: 4,
        pitStopTime: 0.89,
      },
      {
        level: 5,
        speed: 5,
        cornering: 16,
        powerUnit: 7,
        qualifying: 5,
        pitStopTime: 0.86,
      },
      {
        level: 6,
        speed: 5,
        cornering: 18,
        powerUnit: 8,
        qualifying: 6,
        pitStopTime: 0.83,
      },
      {
        level: 7,
        speed: 6,
        cornering: 20,
        powerUnit: 9,
        qualifying: 7,
        pitStopTime: 0.81,
      },
      {
        level: 8,
        speed: 7,
        cornering: 23,
        powerUnit: 10,
        qualifying: 7,
        pitStopTime: 0.78,
      },
      {
        level: 9,
        speed: 8,
        cornering: 25,
        powerUnit: 11,
        qualifying: 8,
        pitStopTime: 0.76,
      },
    ],
  },
  {
    id: 2,
    name: 'The Spire',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        speed: 5,
        cornering: 6,
        powerUnit: 3,
        qualifying: 4,
        pitStopTime: 0.79,
      },
      {
        level: 2,
        speed: 6,
        cornering: 7,
        powerUnit: 4,
        qualifying: 5,
        pitStopTime: 0.76,
      },
      {
        level: 3,
        speed: 6,
        cornering: 8,
        powerUnit: 5,
        qualifying: 6,
        pitStopTime: 0.73,
      },
      {
        level: 4,
        speed: 7,
        cornering: 8,
        powerUnit: 6,
        qualifying: 7,
        pitStopTime: 0.70,
      },
      {
        level: 5,
        speed: 8,
        cornering: 9,
        powerUnit: 7,
        qualifying: 8,
        pitStopTime: 0.66,
      },
      {
        level: 6,
        speed: 9,
        cornering: 10,
        powerUnit: 8,
        qualifying: 9,
        pitStopTime: 0.63,
      },
      {
        level: 7,
        speed: 9,
        cornering: 11,
        powerUnit: 9,
        qualifying: 9,
        pitStopTime: 0.60,
      },
      {
        level: 8,
        speed: 10,
        cornering: 12,
        powerUnit: 10,
        qualifying: 10,
        pitStopTime: 0.57,
      },
      {
        level: 9,
        speed: 11,
        cornering: 12,
        powerUnit: 11,
        qualifying: 11,
        pitStopTime: 0.54,
      },
      {
        level: 10,
        speed: 11,
        cornering: 13,
        powerUnit: 12,
        qualifying: 12,
        pitStopTime: 0.51,
      },
      {
        level: 11,
        speed: 12,
        cornering: 14,
        powerUnit: 13,
        qualifying: 13,
        pitStopTime: 0.48,
      },
    ],
  },
  {
    id: 3,
    name: 'Motion',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        speed: 4,
        cornering: 2,
        powerUnit: 10,
        qualifying: 3,
        pitStopTime: 0.65,
      },
      {
        level: 2,
        speed: 5,
        cornering: 3,
        powerUnit: 11,
        qualifying: 4,
        pitStopTime: 0.61,
      },
      {
        level: 3,
        speed: 6,
        cornering: 3,
        powerUnit: 12,
        qualifying: 5,
        pitStopTime: 0.57,
      },
      {
        level: 4,
        speed: 6,
        cornering: 4,
        powerUnit: 13,
        qualifying: 5,
        pitStopTime: 0.53,
      },
      {
        level: 5,
        speed: 7,
        cornering: 4,
        powerUnit: 14,
        qualifying: 6,
        pitStopTime: 0.50,
      },
      {
        level: 6,
        speed: 8,
        cornering: 5,
        powerUnit: 16,
        qualifying: 7,
        pitStopTime: 0.46,
      },
      {
        level: 7,
        speed: 9,
        cornering: 6,
        powerUnit: 17,
        qualifying: 8,
        pitStopTime: 0.42,
      },
      {
        level: 8,
        speed: 10,
        cornering: 6,
        powerUnit: 18,
        qualifying: 9,
        pitStopTime: 0.38,
      },
      {
        level: 9,
        speed: 10,
        cornering: 7,
        powerUnit: 19,
        qualifying: 9,
        pitStopTime: 0.34,
      },
      {
        level: 10,
        speed: 11,
        cornering: 7,
        powerUnit: 20,
        qualifying: 10,
        pitStopTime: 0.30,
      },
      {
        level: 11,
        speed: 12,
        cornering: 8,
        powerUnit: 21,
        qualifying: 11,
        pitStopTime: 0.27,
      },
    ],
  },
  {
    id: 4,
    name: 'Aero Blade',
    rarity: 'common',
    series: 6,
    stats: [
      {
        level: 1,
        speed: 14,
        cornering: 5,
        powerUnit: 6,
        qualifying: 14,
        pitStopTime: 0.79,
      },
      {
        level: 2,
        speed: 15,
        cornering: 5,
        powerUnit: 7,
        qualifying: 15,
        pitStopTime: 0.77,
      },
      {
        level: 3,
        speed: 17,
        cornering: 6,
        powerUnit: 7,
        qualifying: 17,
        pitStopTime: 0.75,
      },
      {
        level: 4,
        speed: 18,
        cornering: 6,
        powerUnit: 8,
        qualifying: 18,
        pitStopTime: 0.73,
      },
      {
        level: 5,
        speed: 20,
        cornering: 7,
        powerUnit: 8,
        qualifying: 20,
        pitStopTime: 0.71,
      },
      {
        level: 6,
        speed: 21,
        cornering: 7,
        powerUnit: 9,
        qualifying: 21,
        pitStopTime: 0.69,
      },
      {
        level: 7,
        speed: 22,
        cornering: 7,
        powerUnit: 9,
        qualifying: 22,
        pitStopTime: 0.66,
      },
      {
        level: 8,
        speed: 24,
        cornering: 8,
        powerUnit: 10,
        qualifying: 24,
        pitStopTime: 0.64,
      },
      {
        level: 9,
        speed: 25,
        cornering: 8,
        powerUnit: 10,
        qualifying: 25,
        pitStopTime: 0.62,
      },
      {
        level: 10,
        speed: 27,
        cornering: 9,
        powerUnit: 11,
        qualifying: 27,
        pitStopTime: 0.60,
      },
      {
        level: 11,
        speed: 28,
        cornering: 9,
        powerUnit: 11,
        qualifying: 28,
        pitStopTime: 0.58,
      },
    ],
  },
  {
    id: 5,
    name: 'The Valkyrie',
    rarity: 'epic',
    series: 7,
    stats: [
      {
        level: 1,
        speed: 10,
        cornering: 27,
        powerUnit: 11,
        qualifying: 10,
        pitStopTime: 0.72,
      },
      {
        level: 2,
        speed: 11,
        cornering: 30,
        powerUnit: 12,
        qualifying: 11,
        pitStopTime: 0.69,
      },
      {
        level: 3,
        speed: 12,
        cornering: 32,
        powerUnit: 13,
        qualifying: 12,
        pitStopTime: 0.65,
      },
      {
        level: 4,
        speed: 13,
        cornering: 35,
        powerUnit: 14,
        qualifying: 13,
        pitStopTime: 0.62,
      },
      {
        level: 5,
        speed: 14,
        cornering: 37,
        powerUnit: 15,
        qualifying: 14,
        pitStopTime: 0.58,
      },
      {
        level: 6,
        speed: 15,
        cornering: 40,
        powerUnit: 16,
        qualifying: 15,
        pitStopTime: 0.55,
      },
      {
        level: 7,
        speed: 16,
        cornering: 42,
        powerUnit: 17,
        qualifying: 16,
        pitStopTime: 0.51,
      },
      {
        level: 8,
        speed: 17,
        cornering: 45,
        powerUnit: 18,
        qualifying: 17,
        pitStopTime: 0.48,
      },
    ],
  },
  {
    id: 6,
    name: 'Power Lift',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        speed: 12,
        cornering: 10,
        powerUnit: 30,
        qualifying: 12,
        pitStopTime: 0.69,
      },
      {
        level: 2,
        speed: 13,
        cornering: 11,
        powerUnit: 32,
        qualifying: 13,
        pitStopTime: 0.65,
      },
      {
        level: 3,
        speed: 14,
        cornering: 12,
        powerUnit: 35,
        qualifying: 14,
        pitStopTime: 0.62,
      },
      {
        level: 4,
        speed: 15,
        cornering: 13,
        powerUnit: 37,
        qualifying: 15,
        pitStopTime: 0.59,
      },
      {
        level: 5,
        speed: 16,
        cornering: 14,
        powerUnit: 39,
        qualifying: 16,
        pitStopTime: 0.56,
      },
      {
        level: 6,
        speed: 16,
        cornering: 14,
        powerUnit: 41,
        qualifying: 16,
        pitStopTime: 0.53,
      },
      {
        level: 7,
        speed: 17,
        cornering: 15,
        powerUnit: 44,
        qualifying: 17,
        pitStopTime: 0.50,
      },
      {
        level: 8,
        speed: 18,
        cornering: 16,
        powerUnit: 46,
        qualifying: 18,
        pitStopTime: 0.47,
      },
      {
        level: 9,
        speed: 19,
        cornering: 17,
        powerUnit: 48,
        qualifying: 19,
        pitStopTime: 0.44,
      },
    ],
  },
  {
    id: 7,
    name: 'The Cyclone',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        speed: 42,
        cornering: 16,
        powerUnit: 15,
        qualifying: 17,
        pitStopTime: 0.48,
      },
      {
        level: 2,
        speed: 45,
        cornering: 17,
        powerUnit: 16,
        qualifying: 18,
        pitStopTime: 0.45,
      },
      {
        level: 3,
        speed: 47,
        cornering: 18,
        powerUnit: 17,
        qualifying: 19,
        pitStopTime: 0.42,
      },
      {
        level: 4,
        speed: 50,
        cornering: 19,
        powerUnit: 18,
        qualifying: 20,
        pitStopTime: 0.39,
      },
      {
        level: 5,
        speed: 52,
        cornering: 20,
        powerUnit: 18,
        qualifying: 21,
        pitStopTime: 0.36,
      },
      {
        level: 6,
        speed: 55,
        cornering: 21,
        powerUnit: 19,
        qualifying: 22,
        pitStopTime: 0.33,
      },
      {
        level: 7,
        speed: 57,
        cornering: 22,
        powerUnit: 20,
        qualifying: 23,
        pitStopTime: 0.30,
      },
      {
        level: 8,
        speed: 60,
        cornering: 23,
        powerUnit: 21,
        qualifying: 24,
        pitStopTime: 0.27,
      },
    ],
  },
] as Part[];

const createRearWings = () => {
  const rearWingsToSave = preparePartData(REAR_WINGS);

  console.log('Creating rear wings file >>');
  createFile('src/features/parts/constants/rearWings.json', rearWingsToSave);
};

export default createRearWings;
