/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const SUSPENSIONS: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'Zenith',
    rarity: 'epic',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 9,
        cornering: 2,
        powerUnit: 4,
        qualifying: 3,
        pitStopTime: 0.93,
      },
      {
        level: 2,
        speed: 12,
        cornering: 3,
        powerUnit: 5,
        qualifying: 4,
        pitStopTime: 0.90,
      },
      {
        level: 3,
        speed: 14,
        cornering: 4,
        powerUnit: 6,
        qualifying: 5,
        pitStopTime: 0.86,
      },
      {
        level: 4,
        speed: 17,
        cornering: 5,
        powerUnit: 7,
        qualifying: 6,
        pitStopTime: 0.83,
      },
      {
        level: 5,
        speed: 19,
        cornering: 6,
        powerUnit: 9,
        qualifying: 7,
        pitStopTime: 0.79,
      },
      {
        level: 6,
        speed: 22,
        cornering: 7,
        powerUnit: 10,
        qualifying: 8,
        pitStopTime: 0.76,
      },
      {
        level: 7,
        speed: 24,
        cornering: 8,
        powerUnit: 11,
        qualifying: 9,
        pitStopTime: 0.72,
      },
      {
        level: 8,
        speed: 27,
        cornering: 9,
        powerUnit: 12,
        qualifying: 10,
        pitStopTime: 0.69,
      },
    ],
  },
  {
    id: 2,
    name: 'Nexus',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 3,
        cornering: 2,
        powerUnit: 4,
        qualifying: 3,
        pitStopTime: 0.90,
      },
      {
        level: 2,
        speed: 4,
        cornering: 3,
        powerUnit: 5,
        qualifying: 4,
        pitStopTime: 0.86,
      },
      {
        level: 3,
        speed: 5,
        cornering: 4,
        powerUnit: 6,
        qualifying: 5,
        pitStopTime: 0.83,
      },
      {
        level: 4,
        speed: 5,
        cornering: 4,
        powerUnit: 7,
        qualifying: 5,
        pitStopTime: 0.79,
      },
      {
        level: 5,
        speed: 6,
        cornering: 5,
        powerUnit: 8,
        qualifying: 6,
        pitStopTime: 0.76,
      },
      {
        level: 6,
        speed: 7,
        cornering: 6,
        powerUnit: 9,
        qualifying: 7,
        pitStopTime: 0.72,
      },
      {
        level: 7,
        speed: 8,
        cornering: 7,
        powerUnit: 10,
        qualifying: 8,
        pitStopTime: 0.69,
      },
      {
        level: 8,
        speed: 9,
        cornering: 8,
        powerUnit: 11,
        qualifying: 9,
        pitStopTime: 0.65,
      },
      {
        level: 9,
        speed: 9,
        cornering: 8,
        powerUnit: 12,
        qualifying: 9,
        pitStopTime: 0.62,
      },
      {
        level: 10,
        speed: 10,
        cornering: 9,
        powerUnit: 13,
        qualifying: 10,
        pitStopTime: 0.58,
      },
      {
        level: 11,
        speed: 11,
        cornering: 10,
        powerUnit: 14,
        qualifying: 11,
        pitStopTime: 0.55,
      },
    ],
  },
  {
    id: 3,
    name: 'Curver 2.0',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        speed: 4,
        cornering: 7,
        powerUnit: 2,
        qualifying: 7,
        pitStopTime: 0.93,
      },
      {
        level: 2,
        speed: 5,
        cornering: 8,
        powerUnit: 3,
        qualifying: 8,
        pitStopTime: 0.91,
      },
      {
        level: 3,
        speed: 5,
        cornering: 10,
        powerUnit: 3,
        qualifying: 10,
        pitStopTime: 0.89,
      },
      {
        level: 4,
        speed: 6,
        cornering: 11,
        powerUnit: 4,
        qualifying: 11,
        pitStopTime: 0.87,
      },
      {
        level: 5,
        speed: 6,
        cornering: 13,
        powerUnit: 4,
        qualifying: 13,
        pitStopTime: 0.85,
      },
      {
        level: 6,
        speed: 7,
        cornering: 14,
        powerUnit: 5,
        qualifying: 14,
        pitStopTime: 0.83,
      },
      {
        level: 7,
        speed: 7,
        cornering: 15,
        powerUnit: 5,
        qualifying: 15,
        pitStopTime: 0.80,
      },
      {
        level: 8,
        speed: 8,
        cornering: 17,
        powerUnit: 6,
        qualifying: 17,
        pitStopTime: 0.78,
      },
      {
        level: 9,
        speed: 8,
        cornering: 18,
        powerUnit: 6,
        qualifying: 18,
        pitStopTime: 0.76,
      },
      {
        level: 10,
        speed: 9,
        cornering: 20,
        powerUnit: 7,
        qualifying: 20,
        pitStopTime: 0.74,
      },
      {
        level: 11,
        speed: 9,
        cornering: 21,
        powerUnit: 7,
        qualifying: 21,
        pitStopTime: 0.72,
      },
    ],
  },
  {
    id: 4,
    name: 'The Pulse',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        speed: 4,
        cornering: 5,
        powerUnit: 12,
        qualifying: 6,
        pitStopTime: 0.69,
      },
      {
        level: 2,
        speed: 5,
        cornering: 6,
        powerUnit: 14,
        qualifying: 7,
        pitStopTime: 0.64,
      },
      {
        level: 3,
        speed: 5,
        cornering: 6,
        powerUnit: 15,
        qualifying: 7,
        pitStopTime: 0.59,
      },
      {
        level: 4,
        speed: 6,
        cornering: 7,
        powerUnit: 17,
        qualifying: 8,
        pitStopTime: 0.55,
      },
      {
        level: 5,
        speed: 6,
        cornering: 7,
        powerUnit: 18,
        qualifying: 9,
        pitStopTime: 0.50,
      },
      {
        level: 6,
        speed: 7,
        cornering: 8,
        powerUnit: 20,
        qualifying: 10,
        pitStopTime: 0.46,
      },
      {
        level: 7,
        speed: 7,
        cornering: 8,
        powerUnit: 21,
        qualifying: 10,
        pitStopTime: 0.41,
      },
      {
        level: 8,
        speed: 8,
        cornering: 9,
        powerUnit: 23,
        qualifying: 11,
        pitStopTime: 0.37,
      },
      {
        level: 9,
        speed: 8,
        cornering: 9,
        powerUnit: 24,
        qualifying: 12,
        pitStopTime: 0.32,
      },
      {
        level: 10,
        speed: 9,
        cornering: 10,
        powerUnit: 26,
        qualifying: 12,
        pitStopTime: 0.28,
      },
      {
        level: 11,
        speed: 9,
        cornering: 10,
        powerUnit: 27,
        qualifying: 13,
        pitStopTime: 0.23,
      },
    ],
  },
  {
    id: 5,
    name: 'Hustle',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        speed: 24,
        cornering: 7,
        powerUnit: 11,
        qualifying: 10,
        pitStopTime: 0.76,
      },
      {
        level: 2,
        speed: 26,
        cornering: 8,
        powerUnit: 12,
        qualifying: 11,
        pitStopTime: 0.73,
      },
      {
        level: 3,
        speed: 29,
        cornering: 9,
        powerUnit: 13,
        qualifying: 12,
        pitStopTime: 0.70,
      },
      {
        level: 4,
        speed: 31,
        cornering: 10,
        powerUnit: 14,
        qualifying: 13,
        pitStopTime: 0.68,
      },
      {
        level: 5,
        speed: 33,
        cornering: 11,
        powerUnit: 15,
        qualifying: 14,
        pitStopTime: 0.65,
      },
      {
        level: 6,
        speed: 35,
        cornering: 11,
        powerUnit: 15,
        qualifying: 14,
        pitStopTime: 0.62,
      },
      {
        level: 7,
        speed: 38,
        cornering: 12,
        powerUnit: 16,
        qualifying: 15,
        pitStopTime: 0.60,
      },
      {
        level: 8,
        speed: 40,
        cornering: 13,
        powerUnit: 17,
        qualifying: 16,
        pitStopTime: 0.57,
      },
      {
        level: 9,
        speed: 42,
        cornering: 14,
        powerUnit: 18,
        qualifying: 17,
        pitStopTime: 0.55,
      },
    ],
  },
  {
    id: 6,
    name: 'The Arch',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        speed: 12,
        cornering: 30,
        powerUnit: 10,
        qualifying: 11,
        pitStopTime: 0.65,
      },
      {
        level: 2,
        speed: 13,
        cornering: 32,
        powerUnit: 11,
        qualifying: 12,
        pitStopTime: 0.62,
      },
      {
        level: 3,
        speed: 14,
        cornering: 35,
        powerUnit: 12,
        qualifying: 13,
        pitStopTime: 0.59,
      },
      {
        level: 4,
        speed: 15,
        cornering: 37,
        powerUnit: 12,
        qualifying: 14,
        pitStopTime: 0.56,
      },
      {
        level: 5,
        speed: 16,
        cornering: 40,
        powerUnit: 13,
        qualifying: 15,
        pitStopTime: 0.53,
      },
      {
        level: 6,
        speed: 16,
        cornering: 42,
        powerUnit: 14,
        qualifying: 15,
        pitStopTime: 0.50,
      },
      {
        level: 7,
        speed: 17,
        cornering: 44,
        powerUnit: 15,
        qualifying: 16,
        pitStopTime: 0.47,
      },
      {
        level: 8,
        speed: 18,
        cornering: 47,
        powerUnit: 15,
        qualifying: 17,
        pitStopTime: 0.44,
      },
      {
        level: 9,
        speed: 19,
        cornering: 49,
        powerUnit: 16,
        qualifying: 18,
        pitStopTime: 0.41,
      },
    ],
  },
  {
    id: 7,
    name: 'The Reactor',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        speed: 16,
        cornering: 17,
        powerUnit: 42,
        qualifying: 15,
        pitStopTime: 0.48,
      },
      {
        level: 2,
        speed: 17,
        cornering: 18,
        powerUnit: 45,
        qualifying: 16,
        pitStopTime: 0.45,
      },
      {
        level: 3,
        speed: 18,
        cornering: 19,
        powerUnit: 47,
        qualifying: 17,
        pitStopTime: 0.43,
      },
      {
        level: 4,
        speed: 19,
        cornering: 20,
        powerUnit: 50,
        qualifying: 18,
        pitStopTime: 0.40,
      },
      {
        level: 5,
        speed: 20,
        cornering: 21,
        powerUnit: 52,
        qualifying: 19,
        pitStopTime: 0.38,
      },
      {
        level: 6,
        speed: 21,
        cornering: 22,
        powerUnit: 55,
        qualifying: 20,
        pitStopTime: 0.35,
      },
      {
        level: 7,
        speed: 22,
        cornering: 23,
        powerUnit: 57,
        qualifying: 21,
        pitStopTime: 0.33,
      },
      {
        level: 8,
        speed: 23,
        cornering: 24,
        powerUnit: 60,
        qualifying: 22,
        pitStopTime: 0.30,
      },
    ],
  },
] as Part[];

const createSuspensions = () => {
  const suspensionsToSave = preparePartData(SUSPENSIONS);

  console.log('Creating suspensions file >>');
  createFile('src/features/parts/constants/suspensions.json', suspensionsToSave);
};

export default createSuspensions;
